obj-$(CONFIG_SURFACE_SAM_SSH)	+= surface_sam_ssh.o
obj-$(CONFIG_SURFACE_SAM_SAN)	+= surface_sam_san.o
obj-$(CONFIG_SURFACE_SAM_SID)	+= surface_sam_sid.o
obj-$(CONFIG_SURFACE_SAM_DTX)	+= surface_sam_dtx.o
obj-$(CONFIG_SURFACE_SAM_VHF)	+= surface_sam_vhf.o
