# SPDX-License-Identifier: GPL-2.0-or-later
#
# Makefile for the IPTS touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_IPTS) += ipts.o
ipts-objs := control.o
ipts-objs += data.o
ipts-objs += hid.o
ipts-objs += init.o
ipts-objs += math.o
ipts-objs += params.o
ipts-objs += payload.o
ipts-objs += receiver.o
ipts-objs += resources.o
ipts-objs += singletouch.o
ipts-objs += stylus.o
