# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VIDEO_IPU3_CIO2) += ipu3-cio2.o
obj-$(CONFIG_INT3472) += int3472.o

ipu3-cio2-y += ipu3-cio2-main.o
ipu3-cio2-$(CONFIG_CIO2_BRIDGE) += cio2-bridge.o
