# SPDX-License-Identifier: GPL-2.0-or-later

obj-$(CONFIG_SURFACE_AGGREGATOR_DEBUGFS)	+= surface_aggregator_debugfs.o
obj-$(CONFIG_SURFACE_AGGREGATOR_REGISTRY)	+= surface_aggregator_registry.o
obj-$(CONFIG_SURFACE_ACPI_NOTIFY)		+= surface_acpi_notify.o
obj-$(CONFIG_SURFACE_BATTERY)			+= surface_battery.o
obj-$(CONFIG_SURFACE_DTX)			+= surface_dtx.o
obj-$(CONFIG_SURFACE_HID)			+= surface_hid.o
obj-$(CONFIG_SURFACE_HOTPLUG)			+= surface_hotplug.o
obj-$(CONFIG_SURFACE_KEYBOARD)			+= surface_keyboard.o
obj-$(CONFIG_SURFACE_PERFMODE) 			+= surface_perfmode.o
