# SPDX-License-Identifier: GPL-2.0-or-later

obj-$(CONFIG_SURFACE_AGGREGATOR) += surface_aggregator.o

surface_aggregator-objs := core.o
surface_aggregator-objs += ssh_parser.o
surface_aggregator-objs += ssh_packet_layer.o
surface_aggregator-objs += ssh_request_layer.o
surface_aggregator-objs += controller.o
