# SPDX-License-Identifier: GPL-2.0-or-later

obj-$(CONFIG_SURFACE_SAM_DEBUGFS) += surface_sam_debugfs.o
obj-$(CONFIG_SURFACE_SAM_SAN) += surface_sam_san.o
obj-$(CONFIG_SURFACE_SAM_KBD) += surface_sam_vhf.o
obj-$(CONFIG_SURFACE_SAM_DTX) += surface_sam_dtx.o
obj-$(CONFIG_SURFACE_SAM_HPS) += surface_sam_hps.o
obj-$(CONFIG_SURFACE_SAM_PERFMODE) += surface_sam_sid_perfmode.o
obj-$(CONFIG_SURFACE_SAM_HID) += surface_sam_sid_vhf.o
obj-$(CONFIG_SURFACE_SAM_PSY) += surface_sam_sid_power.o
obj-$(CONFIG_SURFACE_SAM_DEVICE_HUB) += surface_sam_device_hub.o
